services:
  rustdesk-api:
    image: lejianwen/rustdesk-api
    container_name: rustdesk-api
    environment:
      - TZ=Asia/Shanghai
      - RUSTDESK_API_RUSTDESK_ID_SERVER=192.168.1.66:31116
      - RUSTDESK_API_RUSTDESK_RELAY_SERVER=192.168.1.66:31117
      - RUSTDESK_API_RUSTDESK_API_SERVER=http://127.0.0.1:31114
      - RUSTDESK_API_RUSTDESK_KEY=123456789
    ports:
      - 31114:31114
    volumes:
      - ./data/rustdesk/api:/app/data # database
      # - ./conf:/app/conf # config
      # - ./resources:/app/resources # 静态资源
    restart: unless-stopped